### ISSUE TITLE
Wrong distrib archive name if release asset is renamed by Github

### ISSUE THREAD

**Issue by leamingrad** [samoht/dune-release#142]
See https://github.com/ocaml/opam-repository/pull/14156

Based on the documentation [here](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) the issue is that the github release API will rename asset that contain special characters (in this case the `+`).

I would be happy to enhance `dune-release` to query the asset names once it has uploaded them, but could do with some guidance on the best way to handle this - should it be done as part of asset upload and stored somewhere or should it be part of the opam release command?

**Comment by NathanReb** [comment]
I ran into this issue before and it is indeed quite annoying.

To make sure I understand the problem correctly:
- During `dune-release publish` the release creation through github's API goes fine as it is okay to use the `+` character in a release name but the URL to the release page is sanitized and that `+` becomes a `%2B`.
- During `dune-release publish` the archive upload through github's API goes fine as well since github sanitize the archive file name on its own
- During `dune-release opam pkg` it blows up as we neither sanitize the path part nor the filename part of the archive download URL and end up, in your case with `https://github.com/cryptosense/ocaml-zxcvbn/releases/download/v2.3+2/zxcvbn-v2.3+2.tbz` instead of `https://github.com/cryptosense/ocaml-zxcvbn/releases/download/v2.3%2B2/zxcvbn-v2.3.2.tbz`

Is that correct?

If so, my gut feeling is that we should generate the right archive filename straight away during `dune-release distrib` so that they don't differ on your filesystem and on github servers, that's confusing to the user. We should then just sanitize the URL path during `dune-release opam pkg`.

Unfortunately the inconvenient with this approach is that we have to maintain the sanitizing functions in `dune-release` instead of just letting github take care of it.

I think the approach you suggest which is to use the github's API responses is both simpler to implement and maintain so let's go for that. We can store it in a `url` file next to the archive in the `_build` directory and use the content of that file to generate the right `opam` file. That means that now `dune-release opam pkg` would depend on `dune-release publish` having been run beforehand which I believe isn't currently the case but I think that's fine. We should probably warn the user if the URL differs from the one we would have generated ourselves btw.

A PR is always welcome of course and I'm happy to help you with that if you need!

**Comment by leamingrad** [comment]
Sorry for the delay in replying to this. I agree with your characterization of the problem above, and will give your PR a try to see if it now works as expected.
