### ISSUE TITLE
Support multi-package publish

### ISSUE THREAD

**Issue by samoht** [samoht/dune-release#3]

**Comment by mor1** [comment]
Related to #7 as well: it would be nice if there were some way to do a multi-package release that submitted all packages to the same `opam-repository` PR. With the recent Owl release I ended up having to close 3 of 4 PRs, and manually merge and push them into the remaining open PR for the `owl-base` package on which the others depended (otherwise the build tests would fail for all but `owl-base`).

**Comment by diml** [comment]
Another case that is currently painful is when we need to add constraints on other packages. Basically, as soon as the PR is not a single new package, you  have to do all the steps manually.

**Comment by samoht** [comment]
So with #26 it is now possible to do:

```
dune-release opam submit -n pkg1,pkg2,...,pkgn
```

Which will submit `pkg1`, `pkg2`, ..., `pkgn` using only one PR.
