### ISSUE TITLE
Improve workflow when odoc is not installed

### ISSUE THREAD

**Issue by samoht** [samoht/dune-release#90]
Instead of failing late, just fail early and/or skip the doc publishing steps.

**Comment by NathanReb** [comment]
I think `publish` should fail if it can't build the doc as the workaround already exists and is to run `dune-release publish distrib`.

My impression is that it should fail fairly early since `dune build @doc` will fail. I'm not sure it is worth adding a check in `dune-release` IF the error reporting in this case is good enough.

We're currently working on the error reporting so I'm closing this. Please feel free to re-open if you believe this isn't a good enough fix.
